#
# Generated by erpcgen 1.8.0 on Thu Oct 22 01:33:52 2020.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for rpc_ble_callback
class Irpc_ble_callback(object):
    SERVICE_ID = 12
    RPC_BLE_HANDLE_GAP_MSG_ID = 1
    RPC_BLE_GAP_CALLBACK_ID = 2
    RPC_BLE_GATTC_CALLBACK_ID = 3
    RPC_BLE_GATTS_CALLBACK_ID = 4

    def rpc_ble_handle_gap_msg(self, gap_msg):
        raise NotImplementedError()

    def rpc_ble_gap_callback(self, cb_type, cb_data):
        raise NotImplementedError()

    def rpc_ble_gattc_callback(self, gatt_if, conn_id, cb_data, extra_data):
        raise NotImplementedError()

    def rpc_ble_gatts_callback(self, gatt_if, conn_id, attrib_index, event, property, read_cb_data, write_cb_data, app_cb_data):
        raise NotImplementedError()


